### ISSUE TITLE
How to configure topic permissions via rabbitmqctl

### ISSUE THREAD

**Issue by USSliberty** [airboxlab/rabbitmq-topic-authorization#2]
I see only an example with the "rabbitmq-auth-backend-http" plugin, but how to configure topic permissions via CLI?

Thank you in advance.

**Comment by antoine-galataud** [comment]
This isn't currently possible with CLI. This plugin is limited to work with external authentication/authorization mechanism.

RabbitMQ is working on integrating topic-based authorization that would work with CLI for 3.7.0. See https://github.com/rabbitmq/rabbitmq-server/issues/505
