### ISSUE TITLE
Compatibility with rabbitmq-auth-backend-cache

### ISSUE THREAD

**Issue by USSliberty** [airboxlab/rabbitmq-topic-authorization#3]
Hi Antonie,
for what concerning cache, this plugin: https://github.com/rabbitmq/rabbitmq-auth-backend-cache 
can work with your plugin?

**Comment by antoine-galataud** [comment]
Hi,

I've never tried myself, but I don't see any reason it wouldn't. It lays between this plugin and the authorization plugin of your choice.
If you have the opportunity to test them all together drop us a word to let us know the outcome of your tests!

**Comment by USSliberty** [comment]
Thank you! I will do a couple of test next week and i will let you know the results.

**Comment by USSliberty** [comment]
I confirm that it works fine. 
But however you need to have at least  Erlang 18.3 (See this topic https://groups.google.com/forum/#!topic/rabbitmq-users/xVHjcEdAY4c)

**Comment by antoine-galataud** [comment]
Great news! I believe that's a possible solution to performance issues that may be encountered with high number of connections/messages. I'll probably take some time soon to benchmark with/without the cache plugin. 

Thank you for the time spent on this.
