### ISSUE TITLE
Please produce a release against 3.6.6

### ISSUE THREAD

**Issue by michaelklishin** [airboxlab/rabbitmq-topic-authorization#4]
The only change should be a `rabbitmq-components.mk` update.

**Comment by antoine-galataud** [comment]
I'm having hard time building against 3.6.6

After applying rabbitmq-components.mk update, I had to add `DEPS = rabbit_common` to Makefile. After that: 

```
$ make
$ make dist
```

The latest command fails with following trace:

```
make[1]: Entering directory '/home/antoine/git/rabbitmq-topic-authorization/deps/rabbit_common'
make[2]: Entering directory '/home/antoine/git/rabbitmq-topic-authorization/deps/lager'
make[3]: Entering directory '/home/antoine/git/rabbitmq-topic-authorization/deps/goldrush'
make[3]: Leaving directory '/home/antoine/git/rabbitmq-topic-authorization/deps/goldrush'
make[2]: Leaving directory '/home/antoine/git/rabbitmq-topic-authorization/deps/lager'
make[2]: Entering directory '/home/antoine/git/rabbitmq-topic-authorization/deps/jsx'
make[2]: Leaving directory '/home/antoine/git/rabbitmq-topic-authorization/deps/jsx'
make[1]: Leaving directory '/home/antoine/git/rabbitmq-topic-authorization/deps/rabbit_common'
make[1]: *** No rule to make target '/home/antoine/git/rabbitmq-topic-authorization/.erlang.mk/list-deps.log'.  Stop.
erlang.mk:6536: recipe for target '/home/antoine/git/rabbitmq-topic-authorization/.erlang.mk/list-deps.log' failed
make: *** [/home/antoine/git/rabbitmq-topic-authorization/.erlang.mk/list-deps.log] Error 2
```

unless I remove the DEPS instruction added to the Makefile.

Also, I didn't find an easy way to build against the plugin against a specific version. Here is what I did:

```
cd deps/rabbit_common
git checkout -b rabbitmq_v3_6_6
cd ../../
make
```

I believe there must be an easier solution.

**Comment by michaelklishin** [comment]
@antoine-galataud you can build against `stable` in the umbrella, I did this for a rabbitmq-users thread yesterday. There are no internal API changes since 3.6.6. I didn't change any Makefiles in the process.

**Comment by antoine-galataud** [comment]
@michaelklishin thanks for the tips. Release done and tested (internally) against rabbitmq-server 3.6.6

**Comment by michaelklishin** [comment]
@antoine-galataud thank you!
